name: Millenial Mindset
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#92a298'
    - '#e6e6cc'
    - '#80dada'
    - '#6e4d3a'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
