name: Millenial Mindset
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130907'
    - '#eeeeec'
    - '#a1a19f'
    - '#464f56'
    - '#7c7771'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
