name: Millenial Mindset
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#95adcf'
    - '#232122'
    - '#7094b8'
    - '#585c5d'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
