name: Millenial Mindset
favicon: null
layout_spectrum: 0.99422
typography_spectrum: 0.43572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#92a298'
    - '#e6e6cc'
    - '#80dada'
    - '#6e4d3a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
